### ISSUE TITLE
Программа закрыта.

### ISSUE THREAD

**Issue by daemonserj** [Ultra-NX/UltraNX#13]
Привет.
Не запускается Agatha Christie — The ABC Murders с раздачи https://rutracker.org/forum/viewtopic.php?t=5951577
Программа закрыта, потому что произошла ошибка.
Запускаю на чипованом Оледе 18.1
Ранее точно работала на лайте 17.0 с ультрой.

**Comment by k1gs** [comment]
Мало информации. Причин много может быть

**Comment by IcePhoenix2456** [comment]
Можно попробовать переустановить сборку. Зачастую решает большинство проблем.

**Comment by redraz** [comment]
За отсутствием дополнительных подробностей - закрываю тикет
