### ISSUE TITLE
Relase time for 19.0.0

### ISSUE THREAD

**Issue by AEZAKMI9432** [Ultra-NX/UltraNX#14]
Hello everyone, when can we expect a release for version 19.0.0 update?

**Comment by zergzorg** [comment]
Hi. Are you in a hurry? Version 19 was only recently released. There’s absolutely nothing in it that would prevent you from staying on version 18, 18.1, or even 17. I myself was using version 17 until recently, and there wasn’t a single game that didn’t work. I updated to version 18.1 the other day, and there’s no noticeable difference. So, don’t worry, I don’t think this is a top priority, and version 18.1 will remain relevant for at least another year.

**Comment by redraz** [comment]
The new atmosphere is not even in pre release yet, not much works on it yet, and it may not be safe to use it for a long time.
If you have updated Stock to 19 HOS, but you still have emunand on <18.1.0 HOS, just re-download/install Ultra 2.2|R4+ via AIO/archive, and unzip to console. After that - go to Hekate - More Configs - Full Stock. After that, you should have emunand running on <18.1.0 without any problems.

If you have updated emunand to 19 HOS, then unpack this test version from the archive to your console, and then go into emunand and roll back the firmware to 18.1.0 by downloading the necessary firmware from AIO and installing it via Daybreak.

[Ultra 2.3 Alpha 19 HOS.zip](https://github.com/user-attachments/files/17387660/Ultra.2.3.Alpha.19.HOS.zip)

**Comment by AEZAKMI9432** [comment]
> Привет. Ты торопишься? Версия 19 вышла совсем недавно. В ней нет абсолютно ничего, что помешало бы тебе остаться на версии 18, 18.1 или даже 17. Я сам до недавнего времени пользовался версией 17, и не было ни одной игры, которая бы не работала. Я обновился до версии 18.1 на днях, и никакой заметной разницы нет. Так что не волнуйся, я не думаю, что это главный приоритет, и версия 18.1 останется актуальной как минимум еще год.

The problem is that I have a console with firmware 19.0.0, which no one has modified. I don't even have any idea what to do with this situation

**Comment by redraz** [comment]
The version for HOS 19 is already out, I remembered the issue, I'm closing it down
