### ISSUE TITLE
Ошибка 2182-0000 (0xb6) 

### ISSUE THREAD

**Issue by Ganesh2556** [Ultra-NX/UltraNX#15]
Здравствуйте.

Свитч ушел в спящий режим и не захотел из него выходить.
Я перезагрузил консоль и поймал ошибку 2182-0000 (0xb6)  program: 0100000000000045
При перезапуске ошибка не уходит.
При загрузке Full-stock он работает.
Карта не извлекалась, обновления не ставил. Устанавливались две игры через Tinfoil

**Comment by redraz** [comment]
Попробуйте произвести [Чистую установку](https://github.com/Ultra-NX/UltraNX/wiki/Installing-RU#чистая-установка), проблема не в Ультре
