### ISSUE TITLE
Edizon не отображает читы, скаченные через AIO 

### ISSUE THREAD

**Issue by Klavishnik** [Ultra-NX/UltraNX#17]

**Comment by redraz** [comment]
Проблема была в фиксе старых форвардеров. Либо работают они, либо читы. Выбор был сделан, теперь читы работают, а форвардеры... Ну, если нужны - сделайте новые, [сайт генератор](https://nsp-forwarder-git-fork-masagrator-main-tootallteam.vercel.app)
