### ISSUE TITLE
Reboot to Full Stock

### ISSUE THREAD

**Issue by organicFoil** [Ultra-NX/UltraNX#19]
Есть возможность как-то добавить пункт перезагрузки в full stock в \switch\.packages\package.ini ?

**Comment by redraz** [comment]
Зачем, если там есть Semi Stock? Если вы не используете моды/читы, и не ставите пиратки, то семи сток безопасен. В любом случае, вот это добавьте в файл

```
[Full Stock    -    Nintendo]
set-ini-val /bootloader/hekate_ipl.ini config autoboot 3
set-ini-val /bootloader/hekate_ipl.ini config autoboot_list 1
reboot
```
