### ISSUE TITLE
Обновить DBI до актуальной версии

### ISSUE THREAD

**Issue by danilvalov** [Ultra-NX/UltraNX#20]
Приветствую!

Как понимаю, у нас в UltraNX 2.3R2 включён DBI версии 658 (от [4 января 2024](https://github.com/rashevskyv/dbi/releases/tag/658)).

Столкнулся с проблемой, что при установке Just Dance 2025 нужно запустить DBI MTP USB в режиме тайтл, чтобы попасть вот в эту папку на компьютере, чтобы закинуть кэш для игры:
`Switch > 7: Saves > Installed games > Just Dance®.`

Как я ни старался, у меня не получилось это сделать (при зажатии кнопки "R" и запуске игры - появляется HBMenu, и при заходе в USB MTP там - папки сохранений там нет).

Предполагаю, что DBI v658 просто не умеет это (доступ к сохранениям у меня в текущем DBI есть только внутри самого DBI и через FTP, и то только к сохранениям одной какой-то игры (к конкретному профилю, не глобальный) или её DLC - это там внутри разделяется).

Поэтому вопросы:
1. Могу ли я сам руками обновить DBI до актуальной версии?
2. Что-то может пойти не так после обновления (предполагаю, DBI не обновляли внутри UltraNX не из-за лени, а из-за каких-то рисков)?
3. Как понимаю, в конфиге DBI для UltraNX много кастомизаций, которые могут быть не совместимы с последней версией DBI, поэтому этот конфиг нужно будет удалить предварительно, верно?

**Comment by redraz** [comment]
Последний актуальный английский DBI - 658, но в Тюнере можно без проблем обновить как DBI до последнего русского (на данный момент 749), так и скачать актуальный рабочий конфиг, с оптимальными настройками и notUltraNX.
L+R+Вверх - Вправо - Ultra Tuner - Software - DBI

**Comment by danilvalov** [comment]
@redraz Большое спасибо! Всё оказалось намного проще, чем я предполагал. Максимально удобно
